version: "1.0"

services:
  web:
    container_name: web
    image: "front-nukerduit:1.0.0"
    ports:
      - "4200:80"
    build:
      context: .
      args:
        - DEPLOY=dev
        - NGINX=nginx.conf
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "14"
        labels: "Local-status"
