version: "1.0"

services:
    app:
        container_name: app
        image: laravel:1.0.0
        build: .
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db
        restart: always

    db:
        container_name: db
        image: postgres:16
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data

    web:
        container_name: pgAdmin
        image: dpage/pgadmin4
        ports:
            - "5050:80"
        depends_on:
            - db
        environment:
            PGADMIN_DEFAULT_EMAIL: test@example.com
            PGADMIN_DEFAULT_PASSWORD: password

volumes:
    pgdata: {}
